name: Container
on:
  pull_request:
    branches:
    - main
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker login -u rfratto -p "${{ secrets.DOCKER_PASS }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull latest container
        run: docker pull rfratto/viceroy:latest
      - name: Make container
        run: OSXCROSS_SDK_URL=${{ secrets.OSXCROSS_SDK_URL }} make build
      - name: Rename container
        run: docker tag rfratto/viceroy:latest rfratto/viceroy:${{ github.ref_name }}
      - name: Push container
        run: docker push rfratto/viceroy:latest rfratto/viceroy:${{ github.ref_name }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
